# Generated by Django 5.2.3 on 2025-06-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ForecastQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecast.forecastdata')),
            ],
        ),
    ]
