# Generated by Django 5.2.3 on 2025-06-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_forecastquery_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastquery',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='forecastquery',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
