# Generated by Django 5.2.3 on 2025-06-28 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_alter_forecastdata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdata',
            name='time',
            field=models.TimeField(choices=[(datetime.time(0, 0), '00'), (datetime.time(1, 0), '01'), (datetime.time(2, 0), '02'), (datetime.time(3, 0), '03'), (datetime.time(4, 0), '04'), (datetime.time(5, 0), '05'), (datetime.time(6, 0), '06'), (datetime.time(7, 0), '07'), (datetime.time(8, 0), '08'), (datetime.time(9, 0), '09'), (datetime.time(10, 0), '10'), (datetime.time(11, 0), '11'), (datetime.time(12, 0), '12'), (datetime.time(13, 0), '13'), (datetime.time(14, 0), '14'), (datetime.time(15, 0), '15'), (datetime.time(16, 0), '16'), (datetime.time(17, 0), '17'), (datetime.time(18, 0), '18'), (datetime.time(19, 0), '19'), (datetime.time(20, 0), '20'), (datetime.time(21, 0), '21'), (datetime.time(22, 0), '22'), (datetime.time(23, 0), '23')]),
        ),
    ]
